### ISSUE TITLE
Create empty table with initiated scheme

### ISSUE THREAD

**Issue by dorianheidorn** [lars-reimann/Safe-DS#306]
### Is your feature request related to a problem? Please describe

When working with Tables, it is not possible to create an empty table with a presetted schema. This is a Problem if the empty table should be used to be filled while working with it because every operation like "add_row()". In this case the schema of both entities, the table and row are not matching.
For further information on why there are mismatching schemas please refer to #296 

### Desired solution

Let schema of an empty table be initially None and change other methods for this functionality.

```py
table = Table([])
table.add_row(Row([1,2])
```

**Comment by WinPlay02** [comment]
For #302: when `split` is called and percentage is 0.0 or 1.0, an empty table is created.

**Comment by dorianheidorn** [comment]
For usability reasons it is more convenient to be able to create an empty table only if you can set the presetted schema. So it is not possible to create a table with no data and no schema
