### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by GideonKoenig** [lars-reimann/Safe-DS#361]
### Is your feature request related to a problem? Please describe

Tutorials hinzufügen.

In PythonLibrary einen Unterreiter Tutorials. Hier dann die entsprechenden Markdown Dokumente mit passendem Namen ablegen und das Inhaltsverzeichnis in mkdocs.yml anpassen.

- [x] Datenverarbeitung (Einlesen, Verarbeiten, Abspeichern) (@Marsmaennchen221, @dorianheidorn)
- [x] Visualisierung (mit Screenshots, bzw. Bild abspeichern) (@GideonKoenig, @SmiteDeluxe)
- [x] Maschinelles Lernen (Model, Supervised Dataset) (@WinPlay02  @Gerhardsa0 )
- [x] Titanic Gesamtbeispiel (@GideonKoenig)

**Comment by lars-reimann** [comment]
Closing this since all linked issues are done.
