### ISSUE TITLE
Minor implementation todos

### ISSUE THREAD

**Issue by lars-reimann** [lars-reimann/Safe-DS#381]
### Is your feature request related to a problem? Please describe

- [x] summary: convert all values to string to prevent the `.00000`
- [x] summary: heading "metrics" for first column
- [x] #395
- [x] heatmap: color scheme should be chose so a correlation of 1 is red, of 0 is white and of -1 is blue. The legend should always have the range -1 to 1.

**Comment by SmiteDeluxe** [comment]
Think the legend range is always -1 to 1, since we map correlations in %, so made no change to this particularly, only color scheme.

**Comment by lars-reimann** [comment]
Closing this since all items are done.
